const { where, Op, fn, col } = require("sequelize");
const { ApiLog } = require("../../models");

exports.getDashboardStats = async (req, res) => {
  try {
    const { range, modelName, conversationId } = req.query;
    const whereClause = {};

    // 1. Build the filters dynamically exactly as before

    if (modelName) whereClause.selectedModel = modelName;
    if (conversationId) whereClause.conversationId = conversationId;
    if (range === "today") {
      const startOfToday = new Date();
      startOfToday.setHours(0, 0, 0, 0);
      whereClause.createdAt = { [Op.gte]: startOfMonth };
    } else if (range === "this_month") {
      const startOfMonth = new Date();
      startOfMonth.setDate(1);
      startOfMonth.setHours(0, 0, 0, 0);
      whereClause.createdAt = { [Op.gte]: startOfMonth };
    }

    // 2. Fetch data from DB using the whereClause (Sequelize handles empty objects perfectly!)
    const kpiMetrics = await ApiLog.findOne({
      where: whereClause,
      attributes: [
        // 1. Cost Saved = SUM(estimated_o1_cost - calculated_cost)
        [
          fn("SUM", literal("estimated_o1_cost - calculated_cost")),
          "totalCostSaved",
        ],

        // 2. Average Latency in Seconds = AVG(latency_ms / 1000.0)
        [fn("AVG", literal("latency_ms / 1000.0")), "avgLatencySeconds"],

        // 3. Total Tokens = SUM(prompt_tokens + completion_tokens)
        [
          fn("SUM", literal("prompt_tokens + completion_tokens")),
          "totalTokensConsumed",
        ],
      ],
      raw: true,
    });

    const mostRoutedModelResult = await ApiLog.findOne({
      where: whereClause,
      attributes: [
        "selectedModel", // Grab the model name
        [fn("COUNT", col("id")), "modelCount"], // Count how many times it shows up
      ],
      group: ["selectedModel"], // Group by the model name
      order: [[literal("modelCount"), "DESC"]], // Highest count first
      raw: true,
    });

    const modelBreakDown = await ApiLog.findAll({
      // 1. Changed to findAll to get a list
      where: whereClause,
      attributes: [
        "selectedModel", // 2. Include the model name so the UI knows which row this belongs to

        // 3. Run the exact same performance math, but isolated per model
        [
          fn("SUM", literal("estimated_o1_cost - calculated_cost")),
          "totalCostSaved",
        ],
        [fn("AVG", literal("latency_ms / 1000.0")), "avgLatencySeconds"],
        [
          fn("SUM", literal("prompt_tokens + completion_tokens")),
          "totalTokensConsumed",
        ],
        [
          fn("COUNT", col("id")),
          "totalRequests", // Extra bonus metric: how many times this specific model was hit
        ],
      ],
      group: ["selectedModel"], // 4. Group by model name so the database splits the math up
      raw: true,
    });

    return res.status(200).json({
      success: true,

      // 1. Active Filters (Lets the UI know exactly what filters are currently applied)
      activeFilters: {
        range: range || "all_time",
        modelName: modelName || "all_models",
        conversationId: conversationId || "all_conversations",
      },

      // 2. KPI Cards (Using the data calculated from our 1st query)
      kpis: {
        totalCostSaved: parseFloat(kpiMetrics?.totalCostSaved || 0).toFixed(2),
        avgLatencySeconds: parseFloat(
          kpiMetrics?.avgLatencySeconds || 0,
        ).toFixed(2),
        totalTokensConsumed: parseInt(kpiMetrics?.totalTokensConsumed || 0, 10),
        mostRoutedModel: mostRoutedModelResult
          ? mostRoutedModelResult.selectedModel
          : "N/A",
      },

      // 3. Table Data (Mapping over the array generated by our 3rd query)
      tableData: modelBreakDown.map((row) => ({
        modelName: row.selectedModel,
        totalRequests: parseInt(row.totalRequests || 0, 10),
        costSaved: parseFloat(row.totalCostSaved || 0).toFixed(2),
        avgLatency: parseFloat(row.avgLatencySeconds || 0).toFixed(2),
        tokensConsumed: parseInt(row.totalTokensConsumed || 0, 10),
      })),
    });
  } catch (error) {
    return res
      .status(500)
      .json({ success: false, message: "Error compiling dashboard stats" });
  }
};
